#!/usr/bin/env bash

REMOTE_HOST="${REMOTE_HOST:-root@62.107.25.198}"
REMOTE_PORT="${REMOTE_PORT:-36731}"
REMOTE_DIR="${REMOTE_DIR:-/workspace/}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519_vastai}"
LOCAL_TUNNEL_PORT="${LOCAL_TUNNEL_PORT:-8080}"
REMOTE_TUNNEL_HOST="${REMOTE_TUNNEL_HOST:-localhost}"
REMOTE_TUNNEL_PORT="${REMOTE_TUNNEL_PORT:-8080}"
