#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
INSTANCE_CONFIG="$SCRIPT_DIR/remote_instance.sh"
TMP_CONFIG="$(mktemp "${INSTANCE_CONFIG}.tmp.XXXXXX")"

cleanup() {
  rm -f "$TMP_CONFIG"
}
trap cleanup EXIT

INSTANCES_JSON="$(vastai show instances --raw)"

VASTAI_INSTANCES_JSON="$INSTANCES_JSON" python3 - "$TMP_CONFIG" <<'PY'
import datetime
import json
import os
import shlex
import sys

config_path = sys.argv[1]

instances = json.loads(os.environ["VASTAI_INSTANCES_JSON"])
if not isinstance(instances, list):
    raise SystemExit("vastai show instances --raw did not return a JSON list")
if len(instances) != 1:
    raise SystemExit(f"Expected exactly 1 Vast.ai instance, found {len(instances)}")

instance = instances[0]
if not isinstance(instance, dict):
    raise SystemExit("Vast.ai instance entry is not a JSON object")

instance_id = instance.get("id")
status = instance.get("actual_status") or instance.get("cur_state") or "unknown"
host = instance.get("public_ipaddr")
if not isinstance(host, str) or not host:
    host = instance.get("ssh_host")
if not isinstance(host, str) or not host:
    raise SystemExit("Vast.ai instance is missing public_ipaddr and ssh_host")

port = None
ports = instance.get("ports")
if isinstance(ports, dict):
    ssh_ports = ports.get("22/tcp")
    if isinstance(ssh_ports, list):
        for binding in ssh_ports:
            if not isinstance(binding, dict):
                continue
            host_port = binding.get("HostPort")
            if isinstance(host_port, str) and host_port:
                port = host_port
                break

if port is None:
    ssh_port = instance.get("ssh_port")
    if isinstance(ssh_port, int):
        port = str(ssh_port)
    elif isinstance(ssh_port, str) and ssh_port:
        port = ssh_port

if port is None:
    raise SystemExit("Vast.ai instance is missing an SSH port")

updated_at = datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds")
values = {
    "VASTAI_REMOTE_HOST": f"root@{host}",
    "VASTAI_REMOTE_PORT": port,
    "VASTAI_INSTANCE_ID": "" if instance_id is None else str(instance_id),
    "VASTAI_INSTANCE_STATUS": str(status),
    "VASTAI_INSTANCE_UPDATED_AT": updated_at,
}

with open(config_path, "w", encoding="utf-8") as config_file:
    config_file.write("# Generated by scripts/update_remote_instance.sh; do not edit.\n")
    for key, value in values.items():
        config_file.write(f"{key}={shlex.quote(value)}\n")
PY

mv "$TMP_CONFIG" "$INSTANCE_CONFIG"
chmod 600 "$INSTANCE_CONFIG"

# shellcheck source=/dev/null
source "$INSTANCE_CONFIG"

echo "Wrote $INSTANCE_CONFIG"
echo "REMOTE_HOST=$VASTAI_REMOTE_HOST"
echo "REMOTE_PORT=$VASTAI_REMOTE_PORT"
